language: node_js

node_js:
- stable

branches:
  only:
  - master

env:
  global:
  - SSH_KEY="deploy_key"
  - GIT_NAME="Travis CI"
  - GIT_EMAIL="sergey@bekrin.me"
  - SOURCE_DIR="dist"
  - DEPLOY_BRANCH="master"

before_install:
- openssl aes-256-cbc -K $encrypted_bfc1d62ee170_key -iv $encrypted_bfc1d62ee170_iv -in travis.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key

script:
- npm run lint
- npm run build

after_success:
- echo "bekrin.me" > dist/CNAME # prevent gh-pages to reset custom domain
- npm run deploy
