language: node_js

node_js:
- stable

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_bfc1d62ee170_key -iv $encrypted_bfc1d62ee170_iv -in travis.enc -out ~\/.ssh/travis -d
- chmod u=rw,og= ~/.ssh/travis
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git --version
- git remote set-url origin git@github.com:sergeybekrin/bekrin.me.git
- git fetch origin -f gh-pages:gh-pages

script:
- npm run lint
- npm run build

after_success:
