language: node_js

node_js:
- stable

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_bfc1d62ee170_key -iv $encrypted_bfc1d62ee170_iv -in travis.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- git remote set-url origin git@github.com:sergeybekrin/bekrin.me.git
- git fetch origin -f gh-pages:gh-pages

script:
- npm run lint
- npm run build

after_success:
- git push origin gh-pages
